# pymysql: el conector que instalaste en el paso 02
import pymysql
# Hace que Django use pymysql como si fuera el driver oficial de MySQL para Python
pymysql.install_as_MySQLdb()

# config: función de python-decouple que lee valores del archivo .env
from decouple import AutoConfig, Csv

"""
Django settings for miproyecto_cbja project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
from django.shortcuts import render
# connection: objeto de Django que expone la configuración de la base de datos activa
from django.db import connection

from pathlib import Path
from urllib.parse import unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PACKAGE_DIR = Path(__file__).resolve().parent

# python-decouple reads .env from the project root, but this project keeps it beside settings.py.
# Support both locations so the app works regardless of where the local env file is stored.
for _env_dir in (BASE_DIR, PACKAGE_DIR):
    if (_env_dir / '.env').exists():
        config = AutoConfig(search_path=_env_dir)
        break
else:
    config = AutoConfig()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY', default='django-insecure-local-development-key')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,.onrender.com', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='https://*.onrender.com', cast=Csv())

if config('RENDER', default=False, cast=bool):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    # apps que Django trae instaladas por defecto (admin, auth, sessions, etc.)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'miproyecto_cbja.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'miproyecto_cbja.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DB_URL = config('DB_URL', default=config('DATABASE_URL', default='')).strip()
DB_HOST = config('DB_HOST', default='').strip()
DB_URL_PARSED = urlparse(DB_URL) if DB_URL and '://' in DB_URL else (urlparse(DB_HOST) if '://' in DB_HOST else None)

if DB_URL_PARSED and DB_URL_PARSED.scheme:
    DB_HOST_VALUE = DB_URL_PARSED.hostname or DB_HOST
    DB_NAME_VALUE = DB_URL_PARSED.path.lstrip('/') or config('DB_NAME', default='')
    DB_USER_VALUE = unquote(DB_URL_PARSED.username or config('DB_USER', default=''))
    DB_PASSWORD_VALUE = unquote(DB_URL_PARSED.password or config('DB_PASSWORD', default=''))
    DB_PORT_VALUE = str(DB_URL_PARSED.port or config('DB_PORT', default='3306'))
elif DB_HOST:
    DB_HOST_VALUE = DB_HOST
    DB_NAME_VALUE = config('DB_NAME', default='')
    DB_USER_VALUE = config('DB_USER', default='')
    DB_PASSWORD_VALUE = config('DB_PASSWORD', default='')
    DB_PORT_VALUE = config('DB_PORT', default='3306')
else:
    DB_HOST_VALUE = ''
    DB_NAME_VALUE = config('DB_NAME', default='')
    DB_USER_VALUE = config('DB_USER', default='')
    DB_PASSWORD_VALUE = config('DB_PASSWORD', default='')
    DB_PORT_VALUE = config('DB_PORT', default='3306')

if DB_HOST_VALUE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB_NAME_VALUE,
            'USER': DB_USER_VALUE,
            'PASSWORD': DB_PASSWORD_VALUE,
            'HOST': DB_HOST_VALUE,
            'PORT': DB_PORT_VALUE,
            'OPTIONS': {'ssl': {'ssl-mode': 'REQUIRED'}},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

